config/routes.rb
Rails.application.routes.draw do
  root 'challenges#index'

  # Routes for specific challenges
  get 'boxes_and_balls', to: 'challenges#boxes_and_balls'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
  end

  def boxes_and_balls
    return unless params[:boxes_number]
    @visual_answer = params[:visual_answer] == 'true'
    @boxes_number = params[:boxes_number].to_i
    if @boxes_number >= 1
      @walks, @steps = calculate_min_walks(@boxes_number)
    else
      flash[:error] = "The number of boxes must be greater than 0."
      return render :boxes_and_balls
    end


  end

  private

  def calculate_min_walks(boxes_number)
    return boxes_number if boxes_number == 1
    boxes = (1..boxes_number).to_a
    groups_info = Challenges::GroupConsecutiveNumbers.call(boxes_number)
    walks = groups_info[:groups].size
    steps = []

    if @visual_answer
      visual_walks = 0
      balls_per_box = groups_info[:group_size] # Get the maximum number of balls you can put initially into the boxes

      # # While there are boxes that still need to be filled
      steps << { boxes: boxes.dup, balls_per_box: 0, walk: visual_walks }
      while boxes.any? { |box| box > 0 }
        # Reduce the capacity of the boxes that can hold balls_per_box
        boxes.map! { |box| box >= balls_per_box ? box - balls_per_box : box }
        visual_walks += 1
        steps << { boxes: boxes.dup, balls_per_box: balls_per_box, walk: visual_walks }
        balls_per_box > 2 ? balls_per_box -= 2 : balls_per_box = 1
      end
    end

    return walks, steps
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/challenges/boxes_and_balls.html.erb
<h1 class="text-2xl font-bold mb-4">Boxes and Balls Challenge</h1>

<!-- Display error message if the number of boxes is less than 1 -->
<% if flash[:error] %>
  <div class="bg-red-500 text-white font-semibold p-2 rounded mb-4 w-1/2 ml-0">
    <%= flash[:error] %>
  </div>
<% end %>

<%= form_with url: boxes_and_balls_path, method: :get, local: true do %>
  <div class="mb-4 flex items-center">
    <label for="n" class="text-sm font-medium text-gray-700 mr-2">Enter the number of boxes:</label>
    <%= text_field_tag :boxes_number, @boxes_number, class: "px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>
  <div class="mb-4">
    <label class="inline-flex items-center">
      <%= check_box_tag :visual_answer, 'true', params[:visual_answer] == 'true', class: 'form-checkbox' %>
      <span class="ml-2 block text-sm font-medium text-gray-700">Do you want a visual representation of the steps?</span>
    </label>
    <p class="text-xs text-gray-700 mt-2">If you try more than 20 boxes, results will not be as clear as fewer boxes.</p>
  </div>

  <%= submit_tag 'Calculate Minimum Walks', class: "bg-indigo-600 text-white px-4 py-2 rounded-md" %>
<% end %>
<br/>
<% if @walks %>
  <div class="mb-4">
    <p class="mt-4 text-lg font-semibold">Minimum number of walks: <%= " #{@walks}" %></p>
  </div>
<% end %>
<% if @visual_answer && @steps %>
  <!-- Visual Representation -->
  <!-- Compact Matrix Representation for Each Step -->
  <div class="grid grid-cols-8 gap-1">
    <% @steps.each do |step| %>
      <!-- Each step is now represented as a single cell -->
      <div class="p-2 border border-gray-300 bg-gray-50 rounded text-center">
        <h3 class="text-sm font-semibold"> <%= step[:walk] == 0 ? "Initial boxes capacities" : "Walk #{step[:walk]}"  %></h3>
        <p class="text-xs text-gray-500 mb-1"> <%=  step[:walk] == 0 ? "" : "Balls Added: #{step[:balls_per_box]}" %></p>
        <div class="text-xs font-mono">[<%= step[:boxes].join('], [') %>]</div>
      </div>
    <% end %>
  </div>

<% end %>
<br/>
<div class="mb-4">
  <%= link_to 'Back', root_path, class: "bg-gray-500 text-white px-4 py-2 rounded-md" %>
</div>

app/views/challenges/index.html.erb
<h1 class="text-3xl font-bold mb-6 text-gray-800">Available Challenges</h1>

<ul class="space-y-4">
  <li>
    <div class="p-5 bg-white shadow-md rounded-lg transition-transform transform hover:scale-105">
      <h2 class="text-lg font-semibold text-gray-900 mb-2">Boxes and Balls Challenge</h2>
      <p class="text-gray-600 mb-4">Test your problem-solving skills with the Boxes and Balls challenge.</p>
      <%= link_to 'Start Challenge', boxes_and_balls_path, class: "inline-block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 transition-all duration-300 ease-in-out" %>
    </div>
  </li>
  <!-- Add more challenges if needed -->
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeSolverApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 text-gray-900">
    <nav class="bg-blue-700 p-6">
      <h1 class="text-white text-xl font-bold">Challenge Solver App</h1>
    </nav>
    <div class="container mx-auto mt-6">
      <%= yield %>
    </div>
  </body>
</html>